os: linux
<<<<<<< HEAD
sudo: required
=======
>>>>>>> 6f6fc3c853952987f1d6ba4e024736430bf3c2d2
language:
- minimal
services:
- docker

jobs:
  include:
    - name: "checks"
      script:
      - docker run  -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/checks.sh
    - name: "tests"
      script:
      - ./scripts/genenv.sh
      - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap:cpp scripts/tests.sh

notifications:
    email: false
